export const SKILL_LIBRARY = [
  {
    id: "elfArrow",
    name: "精灵箭术",
    description: "凝聚风元素形成箭矢，朝最近敌人连射灵风箭，兼具稳定射程与中距离压制能力。",
    color: "#8fdfff",
    unlockCost: 0,
    starterExclusiveId: "arrowPierce",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.64, damage: 56, count: 1, speed: 520, pierce: 0, size: 9, range: 228 },
      { cooldown: 2.44, damage: 60, count: 1, speed: 545, pierce: 0, size: 9, range: 270 },
      { cooldown: 2.28, damage: 80, count: 2, speed: 570, pierce: 1, size: 10, range: 279 },
      { cooldown: 2.12, damage: 106, count: 2, speed: 595, pierce: 1, size: 10, range: 288 },
      { cooldown: 1.96, damage: 132, count: 3, speed: 620, pierce: 2, size: 11, range: 297 },
    ],
    exclusiveUpgrades: [
      {
        id: "arrowPierce",
        name: "流风破甲",
        description: "灵风箭额外获得穿透层数。",
        maxLevel: 3,
        unlockCost: 0,
        startsUnlocked: true,
      },
      {
        id: "arrowTracking",
        name: "风眼锁定",
        description: "箭矢会自动微调轨迹，优先命中不同目标。",
        maxLevel: 1,
        unlockCost: 120,
      },
      {
        id: "arrowVolley",
        name: "林隙齐射",
        description: "每级额外发射 1 支灵风箭。",
        maxLevel: 2,
        unlockCost: 150,
      },
      {
        id: "arrowTailwind",
        name: "尾流加护",
        description: "提升箭矢飞行速度与最大射程。",
        maxLevel: 2,
        unlockCost: 110,
      },
      {
        id: "arrowBurst",
        name: "花冠裂风",
        description: "箭矢伤害显著提升，并带有更强的击退势能。",
        maxLevel: 2,
        unlockCost: 130,
      },
    ],
  },
  {
    id: "flyingSword",
    name: "飞剑术",
    description: "朝最近敌人的方向射出直线飞剑，初始不带追踪效果，命中后消失。",
    color: "#6cb9ff",
    startsUnlocked: true,
    unlockCost: 0,
    starterExclusiveId: "swordPierce",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 0.9, damage: 24, count: 1, speed: 470, pierce: 0, size: 11, range: 430 },
      { cooldown: 0.78, damage: 34, count: 1, speed: 495, pierce: 0, size: 12, range: 450 },
      { cooldown: 0.7, damage: 46, count: 2, speed: 520, pierce: 1, size: 13, range: 470 },
      { cooldown: 0.62, damage: 59, count: 2, speed: 545, pierce: 1, size: 14, range: 500 },
      { cooldown: 0.54, damage: 74, count: 3, speed: 575, pierce: 2, size: 15, range: 530 },
    ],
    exclusiveUpgrades: [
      {
        id: "swordPierce",
        name: "虹光穿透",
        description: "首次选择即让飞剑获得 1 层穿透，之后每级继续 +1。",
        maxLevel: 3,
        unlockCost: 0,
        startsUnlocked: true,
      },
      {
        id: "swordTracking",
        name: "寻敌剑心",
        description: "飞剑持续追踪目标，转向能力显著增强。",
        maxLevel: 1,
        unlockCost: 130,
      },
      {
        id: "swordGiant",
        name: "巨刃奇袭",
        description: "飞剑有概率化作巨型飞剑，体积、伤害大幅提升且拥有无限射程。",
        maxLevel: 2,
        unlockCost: 180,
      },
      {
        id: "swordGlow",
        name: "亮闪闪",
        description: "飞剑获得明亮发光效果和拖尾高光。",
        maxLevel: 1,
        unlockCost: 90,
      },
      {
        id: "swordGlowColor",
        name: "闪亮亮",
        description: "每次选择都会随机修改一次飞剑的发光颜色。",
        maxLevel: 8,
        unlockCost: 110,
        requiresExclusive: "swordGlow",
        metaPrerequisite: "swordGlow",
      },
    ],
  },
  {
    id: "solarPulse",
    name: "向日脉冲",
    description: "周期性释放灿光波纹，对周围怪物造成范围伤害。",
    color: "#ffd15f",
    unlockCost: 180,
    starterExclusiveId: "solarEcho",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.2, damage: 42, radius: 120, waves: 1, growth: 300 },
      { cooldown: 3.8, damage: 58, radius: 140, waves: 1, growth: 320 },
      { cooldown: 3.4, damage: 76, radius: 160, waves: 2, growth: 340 },
      { cooldown: 3.05, damage: 96, radius: 180, waves: 2, growth: 360 },
      { cooldown: 2.75, damage: 120, radius: 205, waves: 3, growth: 380 },
    ],
    exclusiveUpgrades: [
      {
        id: "solarEcho",
        name: "回响日晕",
        description: "每级额外生成 1 道延迟波纹。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "solarBloom",
        name: "暖阳回春",
        description: "波纹命中敌人时回复少量生命。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "solarScorch",
        name: "焦糖灼痕",
        description: "波纹附带持续灼烧效果。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "bubbleBurst",
    name: "泡泡轰鸣",
    description: "朝怪物发射泡泡弹，命中或飞行结束时爆开。",
    color: "#5bc2d8",
    unlockCost: 220,
    starterExclusiveId: "bubbleSplit",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.8, damage: 36, count: 1, speed: 250, size: 14, splash: 44 },
      { cooldown: 2.45, damage: 48, count: 1, speed: 270, size: 15, splash: 48 },
      { cooldown: 2.15, damage: 64, count: 2, speed: 290, size: 16, splash: 54 },
      { cooldown: 1.92, damage: 82, count: 2, speed: 310, size: 17, splash: 60 },
      { cooldown: 1.68, damage: 104, count: 3, speed: 330, size: 18, splash: 68 },
    ],
    exclusiveUpgrades: [
      {
        id: "bubbleSplit",
        name: "泡泡裂变",
        description: "爆炸后分裂出更多小泡泡追击附近目标。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "bubbleSlow",
        name: "清凉黏附",
        description: "爆炸命中的怪物会被减速。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "bubbleGiant",
        name: "云朵泡影",
        description: "每级显著增加泡泡体积与爆炸范围。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "petalOrbit",
    name: "花瓣回旋",
    description: "让花瓣围绕角色旋转，对靠近的敌人持续切割。",
    color: "#f07f9b",
    unlockCost: 240,
    starterExclusiveId: "petalCount",
    maxLevel: 5,
    statsByLevel: [
      { damage: 18, count: 2, orbitRadius: 68, size: 11, angularSpeed: 2.6 },
      { damage: 26, count: 2, orbitRadius: 72, size: 12, angularSpeed: 2.9 },
      { damage: 36, count: 3, orbitRadius: 78, size: 13, angularSpeed: 3.15 },
      { damage: 48, count: 3, orbitRadius: 84, size: 14, angularSpeed: 3.4 },
      { damage: 62, count: 4, orbitRadius: 90, size: 15, angularSpeed: 3.75 },
    ],
    exclusiveUpgrades: [
      {
        id: "petalCount",
        name: "繁花重影",
        description: "每级额外增加 1 枚花瓣。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "petalBloom",
        name: "盛放外环",
        description: "增大花瓣半径与环绕范围。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "petalSustain",
        name: "花蜜回流",
        description: "花瓣命中怪物时回复少量生命。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "thornVolley",
    name: "荆棘飞簇",
    description: "朝最近敌人扇形射出一组荆棘刺，具备基础穿透能力。",
    color: "#7da44a",
    unlockCost: 260,
    starterExclusiveId: "thornFork",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.4, damage: 22, count: 3, speed: 390, pierce: 1, size: 8, range: 330, spread: 0.22 },
      { cooldown: 2.15, damage: 32, count: 3, speed: 410, pierce: 1, size: 9, range: 350, spread: 0.23 },
      { cooldown: 1.95, damage: 44, count: 4, speed: 430, pierce: 1, size: 9, range: 375, spread: 0.24 },
      { cooldown: 1.78, damage: 57, count: 4, speed: 450, pierce: 2, size: 10, range: 400, spread: 0.25 },
      { cooldown: 1.6, damage: 72, count: 5, speed: 470, pierce: 2, size: 11, range: 430, spread: 0.26 },
    ],
    exclusiveUpgrades: [
      {
        id: "thornFork",
        name: "蔓刺加簇",
        description: "每级额外增加 2 枚荆棘刺。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "thornRoot",
        name: "缠根绞锁",
        description: "荆棘命中后会短暂缠住敌人并显著减速。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "thornBurst",
        name: "棘刺裂响",
        description: "荆棘首次命中后会裂出侧向棘刺。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "dewGarden",
    name: "露水花圃",
    description: "在敌人脚下铺开露水花圃，持续伤害并减速其中的目标。",
    color: "#6fd9c7",
    unlockCost: 280,
    starterExclusiveId: "dewSpread",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 5, damage: 16, radius: 45, duration: 4.4, count: 1, tickInterval: 0.42 },
      { cooldown: 4.55, damage: 22, radius: 49, duration: 4.9, count: 1, tickInterval: 0.4 },
      { cooldown: 4.1, damage: 30, radius: 53, duration: 5.4, count: 2, tickInterval: 0.38 },
      { cooldown: 3.7, damage: 40, radius: 57, duration: 5.9, count: 2, tickInterval: 0.36 },
      { cooldown: 3.3, damage: 52, radius: 62, duration: 6.4, count: 2, tickInterval: 0.34 },
    ],
    exclusiveUpgrades: [
      {
        id: "dewSpread",
        name: "雨露扩繁",
        description: "每级额外生成 1 片露水花圃。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "dewChill",
        name: "凝露迟滞",
        description: "露水花圃会持续强化减速效果。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "dewMend",
        name: "晨露回甘",
        description: "花圃命中敌人时为玩家回复少量生命。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "stormBloom",
    name: "雷芽裁决",
    description: "锁定最近敌人的位置，短暂延迟后降下雷击。",
    color: "#e8da7d",
    unlockCost: 300,
    starterExclusiveId: "stormCount",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.4, damage: 58, radius: 52, count: 1, delay: 0.72 },
      { cooldown: 3.95, damage: 76, radius: 58, count: 1, delay: 0.64 },
      { cooldown: 3.55, damage: 98, radius: 64, count: 2, delay: 0.56 },
      { cooldown: 3.15, damage: 123, radius: 70, count: 2, delay: 0.5 },
      { cooldown: 2.8, damage: 152, radius: 78, count: 2, delay: 0.44 },
    ],
    exclusiveUpgrades: [
      {
        id: "stormCount",
        name: "连株追雷",
        description: "每级额外追加 1 道落雷。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "stormChain",
        name: "电弧续命",
        description: "落雷命中后会向附近敌人跳跃电弧。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "stormField",
        name: "感电花幕",
        description: "落雷后留下短暂感电区域。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "mushroomMine",
    name: "蘑菇伏雷",
    description: "在角色周围种下蘑菇地雷，敌人靠近后会自动爆炸。",
    color: "#c98d5a",
    unlockCost: 320,
    starterExclusiveId: "mineStock",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.8, damage: 72, radius: 62, count: 1, armTime: 0.6, duration: 8 },
      { cooldown: 4.3, damage: 92, radius: 68, count: 1, armTime: 0.56, duration: 8.6 },
      { cooldown: 3.85, damage: 118, radius: 74, count: 2, armTime: 0.5, duration: 9.2 },
      { cooldown: 3.45, damage: 148, radius: 80, count: 2, armTime: 0.46, duration: 9.7 },
      { cooldown: 3.1, damage: 182, radius: 88, count: 3, armTime: 0.42, duration: 10.2 },
    ],
    exclusiveUpgrades: [
      {
        id: "mineStock",
        name: "孢床扩建",
        description: "每级额外布置 1 枚蘑菇地雷。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "mineToxic",
        name: "菌雾残留",
        description: "蘑菇地雷爆炸后会留下毒雾。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "mineBurst",
        name: "爆伞蘑潮",
        description: "地雷爆炸范围增大，并射出孢子破片。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "vineSnare",
    name: "藤鞭绞猎",
    description: "向附近怪物甩出带刺藤鞭，瞬间抽打并缠住目标。",
    color: "#74c26a",
    unlockCost: 340,
    starterExclusiveId: "vineCount",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.6, damage: 48, count: 2, range: 280, root: 0.9, bloomRadius: 52 },
      { cooldown: 3.2, damage: 62, count: 2, range: 310, root: 1.02, bloomRadius: 56 },
      { cooldown: 2.85, damage: 80, count: 3, range: 340, root: 1.14, bloomRadius: 60 },
      { cooldown: 2.55, damage: 101, count: 3, range: 375, root: 1.28, bloomRadius: 64 },
      { cooldown: 2.25, damage: 126, count: 4, range: 410, root: 1.42, bloomRadius: 70 },
    ],
    exclusiveUpgrades: [
      {
        id: "vineCount",
        name: "繁缠分枝",
        description: "每级额外增加 2 条藤鞭。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "vineRoot",
        name: "盘绕定身",
        description: "延长缠绕时间，并额外提高抽打伤害。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "vineBloom",
        name: "荆花爆绽",
        description: "藤鞭命中处会炸开花棘，对周围敌人造成额外伤害。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "meteorSeed",
    name: "彗种坠雨",
    description: "召来带尾焰的种星，从空中坠落并砸向敌群。",
    color: "#ff9867",
    unlockCost: 360,
    starterExclusiveId: "meteorCount",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 5.4, damage: 70, radius: 54, count: 1, fallTime: 0.82 },
      { cooldown: 4.95, damage: 92, radius: 60, count: 1, fallTime: 0.74 },
      { cooldown: 4.5, damage: 118, radius: 66, count: 2, fallTime: 0.66 },
      { cooldown: 4.05, damage: 148, radius: 72, count: 2, fallTime: 0.58 },
      { cooldown: 3.65, damage: 184, radius: 80, count: 3, fallTime: 0.5 },
    ],
    exclusiveUpgrades: [
      {
        id: "meteorCount",
        name: "流星育种",
        description: "每级额外追加 1 枚种星。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "meteorScorch",
        name: "焦土花坑",
        description: "种星坠地后留下灼烧花坑。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "meteorShard",
        name: "碎芒迸射",
        description: "种星撞击后会向外迸出碎芒破片。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "ribbonBlade",
    name: "绫刃回潮",
    description: "抛出回旋丝刃，飞出后折返角色并沿途反复切割。",
    color: "#8f9fff",
    unlockCost: 380,
    starterExclusiveId: "ribbonCount",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.95, damage: 32, count: 1, speed: 360, size: 10, range: 250, pierce: 2 },
      { cooldown: 2.6, damage: 44, count: 1, speed: 385, size: 11, range: 270, pierce: 2 },
      { cooldown: 2.28, damage: 58, count: 2, speed: 410, size: 12, range: 290, pierce: 2 },
      { cooldown: 1.98, damage: 74, count: 2, speed: 435, size: 13, range: 315, pierce: 3 },
      { cooldown: 1.72, damage: 92, count: 3, speed: 460, size: 14, range: 340, pierce: 3 },
    ],
    exclusiveUpgrades: [
      {
        id: "ribbonCount",
        name: "绫轮增幅",
        description: "每级额外增加 1 枚回旋丝刃。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "ribbonReturn",
        name: "回潮切返",
        description: "返程速度、伤害与穿透能力都会增强。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "ribbonFray",
        name: "碎绫飞岚",
        description: "丝刃命中时会裂出侧向碎绫。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "lotusBeacon",
    name: "莲灯守望",
    description: "在战场点亮莲灯，持续锁定附近敌人并射出灵辉。",
    color: "#f4c86d",
    unlockCost: 400,
    starterExclusiveId: "lotusCount",
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 6.2, damage: 26, count: 1, duration: 6.2, interval: 0.95, range: 250 },
      { cooldown: 5.6, damage: 34, count: 1, duration: 6.8, interval: 0.88, range: 280 },
      { cooldown: 5.0, damage: 44, count: 2, duration: 7.4, interval: 0.8, range: 310 },
      { cooldown: 4.45, damage: 56, count: 2, duration: 8.0, interval: 0.72, range: 340 },
      { cooldown: 3.95, damage: 70, count: 2, duration: 8.8, interval: 0.64, range: 380 },
    ],
    exclusiveUpgrades: [
      {
        id: "lotusCount",
        name: "双芯点灯",
        description: "每级额外点亮 1 盏莲灯。",
        maxLevel: 2,
        unlockCost: 0,
      },
      {
        id: "lotusChain",
        name: "莲辉转经",
        description: "莲灯射出的灵辉会继续跳向附近敌人。",
        maxLevel: 2,
        unlockCost: 120,
      },
      {
        id: "lotusWard",
        name: "心莲护祷",
        description: "灵辉命中后减速敌人，并为角色回复少量生命。",
        maxLevel: 2,
        unlockCost: 140,
      },
    ],
  },
  {
    id: "glassPrismRay",
    name: "棱镜折射",
    description: "射出棱镜光束，命中后分裂折射至附近目标。",
    color: "#7fd8ff",
    advancedBehavior: "beam",
    unlockCost: 420,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 1.9, damage: 48, count: 1, speed: 580, pierce: 0, size: 7, range: 400 },
      { cooldown: 1.7, damage: 60, count: 1, speed: 610, pierce: 0, size: 8, range: 430 },
      { cooldown: 1.55, damage: 76, count: 2, speed: 640, pierce: 1, size: 9, range: 460 },
      { cooldown: 1.4, damage: 94, count: 2, speed: 670, pierce: 1, size: 10, range: 490 },
      { cooldown: 1.25, damage: 116, count: 3, speed: 700, pierce: 2, size: 11, range: 520 },
    ],
    exclusiveUpgrades: [
      {
        id: "glassPrismRayFocus",
        name: "棱镜聚焦",
        description: "提高折射光束的基础伤害。",
        maxLevel: 2,
        unlockCost: 124,
      },
      {
        id: "glassPrismRayTempo",
        name: "折光加速",
        description: "缩短棱镜折射的冷却时间。",
        maxLevel: 2,
        unlockCost: 144,
      },
    ],
  },
  {
    id: "honeyBomb",
    name: "蜜弹爆溅",
    description: "丢出蜜糖炸弹，爆炸后留下蜜沼减速敌人。",
    color: "#f0b95f",
    advancedBehavior: "lobbedBomb",
    unlockCost: 448,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.2, damage: 52, count: 1, speed: 240, size: 14, splash: 50, range: 280 },
      { cooldown: 2.9, damage: 66, count: 1, speed: 260, size: 15, splash: 56, range: 300 },
      { cooldown: 2.6, damage: 82, count: 2, speed: 280, size: 16, splash: 62, range: 320 },
      { cooldown: 2.35, damage: 100, count: 2, speed: 300, size: 17, splash: 68, range: 340 },
      { cooldown: 2.1, damage: 122, count: 2, speed: 320, size: 18, splash: 76, range: 360 },
    ],
    exclusiveUpgrades: [
      {
        id: "honeyBombFocus",
        name: "蜜糖浓缩",
        description: "提高蜜弹爆炸的基础伤害。",
        maxLevel: 2,
        unlockCost: 128,
      },
      {
        id: "honeyBombTempo",
        name: "速调蜜浆",
        description: "缩短蜜弹爆溅的冷却时间。",
        maxLevel: 2,
        unlockCost: 148,
      },
    ],
  },
  {
    id: "rainRootSigil",
    name: "雨根符印",
    description: "铭刻雨之符印，治疗角色并伤害踏入的敌人。",
    color: "#78d4b5",
    advancedBehavior: "field",
    unlockCost: 476,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.6, damage: 12, count: 1, radius: 70, duration: 4.0, tickInterval: 0.42 },
      { cooldown: 4.2, damage: 18, count: 1, radius: 78, duration: 4.6, tickInterval: 0.4 },
      { cooldown: 3.8, damage: 26, count: 2, radius: 86, duration: 5.2, tickInterval: 0.38 },
      { cooldown: 3.4, damage: 36, count: 2, radius: 94, duration: 5.8, tickInterval: 0.36 },
      { cooldown: 3.0, damage: 48, count: 2, radius: 104, duration: 6.4, tickInterval: 0.34 },
    ],
    exclusiveUpgrades: [
      {
        id: "rainRootSigilFocus",
        name: "甘霖灌注",
        description: "提高符印的治疗与伤害。",
        maxLevel: 2,
        unlockCost: 132,
      },
      {
        id: "rainRootSigilTempo",
        name: "雨痕速绘",
        description: "缩短雨根符印的冷却时间。",
        maxLevel: 2,
        unlockCost: 152,
      },
    ],
  },
  {
    id: "orchidComet",
    name: "兰彗坠闪",
    description: "召唤兰色彗星坠落，绽放出绽弹飞散。",
    color: "#d69cff",
    advancedBehavior: "meteor",
    unlockCost: 504,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 5.6, damage: 82, radius: 52, count: 1, fallTime: 0.78 },
      { cooldown: 5.1, damage: 104, radius: 58, count: 1, fallTime: 0.7 },
      { cooldown: 4.6, damage: 130, radius: 64, count: 2, fallTime: 0.62 },
      { cooldown: 4.15, damage: 160, radius: 70, count: 2, fallTime: 0.54 },
      { cooldown: 3.75, damage: 196, radius: 78, count: 3, fallTime: 0.46 },
    ],
    exclusiveUpgrades: [
      {
        id: "orchidCometFocus",
        name: "兰花绽放",
        description: "提高彗星伤害与绽弹数量。",
        maxLevel: 2,
        unlockCost: 136,
      },
      {
        id: "orchidCometTempo",
        name: "流星引信",
        description: "缩短兰彗坠闪的冷却时间。",
        maxLevel: 2,
        unlockCost: 156,
      },
    ],
  },
  {
    id: "brambleBoomerang",
    name: "棘蔓回镖",
    description: "投出回旋镖，沿路撒下棘刺种子。",
    color: "#9bcf63",
    advancedBehavior: "boomerang",
    unlockCost: 532,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.0, damage: 38, count: 1, speed: 340, size: 10, range: 240, pierce: 2 },
      { cooldown: 2.7, damage: 50, count: 1, speed: 360, size: 11, range: 260, pierce: 2 },
      { cooldown: 2.4, damage: 64, count: 2, speed: 380, size: 12, range: 280, pierce: 3 },
      { cooldown: 2.15, damage: 80, count: 2, speed: 400, size: 13, range: 300, pierce: 3 },
      { cooldown: 1.9, damage: 98, count: 2, speed: 420, size: 14, range: 320, pierce: 4 },
    ],
    exclusiveUpgrades: [
      {
        id: "brambleBoomerangFocus",
        name: "棘刺淬毒",
        description: "提高回镖与荆棘的伤害。",
        maxLevel: 2,
        unlockCost: 140,
      },
      {
        id: "brambleBoomerangTempo",
        name: "蔓藤回旋",
        description: "缩短棘蔓回镖的冷却时间。",
        maxLevel: 2,
        unlockCost: 160,
      },
    ],
  },
  {
    id: "dewdropMine",
    name: "露珠雷种",
    description: "埋藏露珠地雷，触发时爆炸并回复角色生命。",
    color: "#8adfd6",
    advancedBehavior: "mine",
    unlockCost: 560,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.8, damage: 62, radius: 58, count: 1, armTime: 0.54, duration: 7.5 },
      { cooldown: 4.35, damage: 80, radius: 64, count: 1, armTime: 0.5, duration: 8.0 },
      { cooldown: 3.9, damage: 102, radius: 70, count: 2, armTime: 0.46, duration: 8.5 },
      { cooldown: 3.5, damage: 126, radius: 76, count: 2, armTime: 0.42, duration: 9.0 },
      { cooldown: 3.15, damage: 154, radius: 84, count: 2, armTime: 0.38, duration: 9.5 },
    ],
    exclusiveUpgrades: [
      {
        id: "dewdropMineFocus",
        name: "晨露精萃",
        description: "提高地雷伤害与治疗量。",
        maxLevel: 2,
        unlockCost: 144,
      },
      {
        id: "dewdropMineTempo",
        name: "露种速播",
        description: "缩短露珠雷种的冷却时间。",
        maxLevel: 2,
        unlockCost: 164,
      },
    ],
  },
  {
    id: "stormRibbon",
    name: "风暴绫带",
    description: "召来雷暴绫带横扫战场路径上的所有敌人。",
    color: "#9fb8ff",
    advancedBehavior: "strike",
    unlockCost: 588,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.2, damage: 52, count: 1, radius: 48, delay: 0.48 },
      { cooldown: 3.8, damage: 68, count: 1, radius: 54, delay: 0.42 },
      { cooldown: 3.4, damage: 88, count: 2, radius: 60, delay: 0.36 },
      { cooldown: 3.0, damage: 110, count: 2, radius: 66, delay: 0.3 },
      { cooldown: 2.7, damage: 136, count: 2, radius: 74, delay: 0.24 },
    ],
    exclusiveUpgrades: [
      {
        id: "stormRibbonFocus",
        name: "雷绫蓄能",
        description: "提高风暴绫带的闪电伤害。",
        maxLevel: 2,
        unlockCost: 148,
      },
      {
        id: "stormRibbonTempo",
        name: "风绫疾舞",
        description: "缩短风暴绫带的冷却时间。",
        maxLevel: 2,
        unlockCost: 168,
      },
    ],
  },
  {
    id: "moonwellSnare",
    name: "月泉缠缚",
    description: "召唤月泉之藤缠绕并拖拽敌人。",
    color: "#ef91c2",
    advancedBehavior: "snare",
    unlockCost: 616,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.8, damage: 52, count: 2, range: 260, root: 0.84, bloomRadius: 48 },
      { cooldown: 3.4, damage: 68, count: 2, range: 290, root: 0.96, bloomRadius: 52 },
      { cooldown: 3.0, damage: 88, count: 3, range: 320, root: 1.08, bloomRadius: 56 },
      { cooldown: 2.7, damage: 110, count: 3, range: 350, root: 1.2, bloomRadius: 60 },
      { cooldown: 2.4, damage: 136, count: 3, range: 380, root: 1.34, bloomRadius: 66 },
    ],
    exclusiveUpgrades: [
      {
        id: "moonwellSnareFocus",
        name: "泉涌藤劲",
        description: "提高缠缚伤害与牵引力度。",
        maxLevel: 2,
        unlockCost: 152,
      },
      {
        id: "moonwellSnareTempo",
        name: "月华速生",
        description: "缩短月泉缠缚的冷却时间。",
        maxLevel: 2,
        unlockCost: 172,
      },
    ],
  },
  {
    id: "lanternSpark",
    name: "灯芯火种",
    description: "射出灯芯火花烙印敌人，击杀时爆炸。",
    color: "#f4c86d",
    advancedBehavior: "beam",
    unlockCost: 644,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.0, damage: 38, count: 1, speed: 540, pierce: 0, size: 8, range: 380 },
      { cooldown: 1.8, damage: 50, count: 1, speed: 570, pierce: 0, size: 9, range: 410 },
      { cooldown: 1.6, damage: 64, count: 2, speed: 600, pierce: 1, size: 10, range: 440 },
      { cooldown: 1.45, damage: 80, count: 2, speed: 630, pierce: 1, size: 11, range: 470 },
      { cooldown: 1.3, damage: 100, count: 2, speed: 660, pierce: 2, size: 12, range: 500 },
    ],
    exclusiveUpgrades: [
      {
        id: "lanternSparkFocus",
        name: "灯印灼烧",
        description: "提高灯芯火种的伤害与灼烧效果。",
        maxLevel: 2,
        unlockCost: 156,
      },
      {
        id: "lanternSparkTempo",
        name: "火星飞溅",
        description: "缩短灯芯火种的冷却时间。",
        maxLevel: 2,
        unlockCost: 176,
      },
    ],
  },
  {
    id: "harvestCrescent",
    name: "镰月回旋",
    description: "掷出新月镰刀贯穿敌人，返回时提升移速。",
    color: "#ee7778",
    advancedBehavior: "boomerang",
    unlockCost: 672,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.9, damage: 44, count: 1, speed: 350, size: 11, range: 260, pierce: 3 },
      { cooldown: 2.6, damage: 58, count: 1, speed: 375, size: 12, range: 280, pierce: 3 },
      { cooldown: 2.3, damage: 74, count: 2, speed: 400, size: 13, range: 300, pierce: 3 },
      { cooldown: 2.05, damage: 92, count: 2, speed: 425, size: 14, range: 325, pierce: 4 },
      { cooldown: 1.8, damage: 114, count: 2, speed: 450, size: 15, range: 350, pierce: 4 },
    ],
    exclusiveUpgrades: [
      {
        id: "harvestCrescentFocus",
        name: "镰刃淬锋",
        description: "提高新月镰刀的伤害。",
        maxLevel: 2,
        unlockCost: 160,
      },
      {
        id: "harvestCrescentTempo",
        name: "割刈韵律",
        description: "缩短镰月回旋的冷却时间。",
        maxLevel: 2,
        unlockCost: 180,
      },
    ],
  },
  {
    id: "seedvaultPulse",
    name: "种库脉冲",
    description: "释放种库脉冲，发射追踪芽种追击敌人。",
    color: "#badb69",
    advancedBehavior: "pulse",
    unlockCost: 700,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.4, damage: 36, radius: 120, waves: 1, growth: 300 },
      { cooldown: 4.0, damage: 50, radius: 140, waves: 1, growth: 320 },
      { cooldown: 3.6, damage: 66, radius: 160, waves: 2, growth: 340 },
      { cooldown: 3.2, damage: 84, radius: 180, waves: 2, growth: 360 },
      { cooldown: 2.9, damage: 106, radius: 200, waves: 2, growth: 380 },
    ],
    exclusiveUpgrades: [
      {
        id: "seedvaultPulseFocus",
        name: "种库丰收",
        description: "提高脉冲与芽种伤害。",
        maxLevel: 2,
        unlockCost: 164,
      },
      {
        id: "seedvaultPulseTempo",
        name: "脉冲加速",
        description: "缩短种库脉冲的冷却时间。",
        maxLevel: 2,
        unlockCost: 184,
      },
    ],
  },
  {
    id: "pearlBubble",
    name: "珠泡迸裂",
    description: "吹出珍珠泡沫吸附敌人后爆裂溅射。",
    color: "#f1d18a",
    advancedBehavior: "lobbedBomb",
    unlockCost: 728,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.0, damage: 44, count: 1, speed: 230, size: 15, splash: 46, range: 270 },
      { cooldown: 2.7, damage: 56, count: 1, speed: 250, size: 16, splash: 52, range: 290 },
      { cooldown: 2.4, damage: 72, count: 2, speed: 270, size: 17, splash: 58, range: 310 },
      { cooldown: 2.15, damage: 90, count: 2, speed: 290, size: 18, splash: 64, range: 330 },
      { cooldown: 1.9, damage: 112, count: 2, speed: 310, size: 19, splash: 72, range: 350 },
    ],
    exclusiveUpgrades: [
      {
        id: "pearlBubbleFocus",
        name: "珍珠增厚",
        description: "提高泡沫伤害与吸引范围。",
        maxLevel: 2,
        unlockCost: 168,
      },
      {
        id: "pearlBubbleTempo",
        name: "泡影速成",
        description: "缩短珠泡迸裂的冷却时间。",
        maxLevel: 2,
        unlockCost: 188,
      },
    ],
  },
  {
    id: "clockIvyLash",
    name: "时藤鞭击",
    description: "甩出时间蔓藤抽打区域，延时引爆。",
    color: "#7bc489",
    advancedBehavior: "snare",
    unlockCost: 756,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.6, damage: 56, count: 2, range: 260, root: 0.7, bloomRadius: 50 },
      { cooldown: 3.2, damage: 72, count: 2, range: 290, root: 0.82, bloomRadius: 54 },
      { cooldown: 2.85, damage: 92, count: 3, range: 320, root: 0.94, bloomRadius: 58 },
      { cooldown: 2.55, damage: 114, count: 3, range: 350, root: 1.06, bloomRadius: 62 },
      { cooldown: 2.25, damage: 140, count: 3, range: 380, root: 1.2, bloomRadius: 68 },
    ],
    exclusiveUpgrades: [
      {
        id: "clockIvyLashFocus",
        name: "时藤毒素",
        description: "提高藤鞭伤害与爆炸范围。",
        maxLevel: 2,
        unlockCost: 172,
      },
      {
        id: "clockIvyLashTempo",
        name: "藤蔓速长",
        description: "缩短时藤鞭击的冷却时间。",
        maxLevel: 2,
        unlockCost: 192,
      },
    ],
  },
  {
    id: "operaMothBlade",
    name: "蛾刃回旋",
    description: "放出蛾形飞刃沿螺旋轨迹切割敌人。",
    color: "#c6a0f2",
    advancedBehavior: "boomerang",
    unlockCost: 784,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.2, damage: 36, count: 1, speed: 320, size: 10, range: 260, pierce: 3 },
      { cooldown: 2.9, damage: 48, count: 1, speed: 340, size: 11, range: 280, pierce: 3 },
      { cooldown: 2.6, damage: 62, count: 2, speed: 360, size: 12, range: 300, pierce: 3 },
      { cooldown: 2.3, damage: 78, count: 2, speed: 380, size: 13, range: 320, pierce: 4 },
      { cooldown: 2.05, damage: 96, count: 2, speed: 400, size: 14, range: 340, pierce: 4 },
    ],
    exclusiveUpgrades: [
      {
        id: "operaMothBladeFocus",
        name: "蛾翼淬刃",
        description: "提高蛾刃伤害与飞行速度。",
        maxLevel: 2,
        unlockCost: 176,
      },
      {
        id: "operaMothBladeTempo",
        name: "蝶舞加速",
        description: "缩短蛾刃回旋的冷却时间。",
        maxLevel: 2,
        unlockCost: 196,
      },
    ],
  },
  {
    id: "antlerBolt",
    name: "鹿角突刺",
    description: "射出鹿角标枪贯穿敌人，分裂追击两侧。",
    color: "#73d1ff",
    advancedBehavior: "beam",
    unlockCost: 812,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.4, damage: 56, count: 1, speed: 500, pierce: 1, size: 9, range: 420 },
      { cooldown: 2.15, damage: 72, count: 1, speed: 530, pierce: 1, size: 10, range: 450 },
      { cooldown: 1.9, damage: 90, count: 2, speed: 560, pierce: 2, size: 11, range: 480 },
      { cooldown: 1.7, damage: 112, count: 2, speed: 590, pierce: 2, size: 12, range: 510 },
      { cooldown: 1.5, damage: 138, count: 2, speed: 620, pierce: 3, size: 13, range: 540 },
    ],
    exclusiveUpgrades: [
      {
        id: "antlerBoltFocus",
        name: "鹿角锋锐",
        description: "提高标枪伤害与分裂范围。",
        maxLevel: 2,
        unlockCost: 180,
      },
      {
        id: "antlerBoltTempo",
        name: "标枪快手",
        description: "缩短鹿角突刺的冷却时间。",
        maxLevel: 2,
        unlockCost: 200,
      },
    ],
  },
  {
    id: "sporeTeacupMine",
    name: "菌杯雾雷",
    description: "埋下菌杯地雷，触发后释放持续伤害的菌雾。",
    color: "#b8c978",
    advancedBehavior: "mine",
    unlockCost: 840,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 5.0, damage: 68, radius: 60, count: 1, armTime: 0.52, duration: 7.0 },
      { cooldown: 4.5, damage: 88, radius: 66, count: 1, armTime: 0.48, duration: 7.5 },
      { cooldown: 4.0, damage: 110, radius: 72, count: 2, armTime: 0.44, duration: 8.0 },
      { cooldown: 3.6, damage: 136, radius: 78, count: 2, armTime: 0.4, duration: 8.5 },
      { cooldown: 3.2, damage: 166, radius: 86, count: 2, armTime: 0.36, duration: 9.0 },
    ],
    exclusiveUpgrades: [
      {
        id: "sporeTeacupMineFocus",
        name: "菌孢浓雾",
        description: "提高地雷与菌雾伤害。",
        maxLevel: 2,
        unlockCost: 184,
      },
      {
        id: "sporeTeacupMineTempo",
        name: "速生菌床",
        description: "缩短菌杯雾雷的冷却时间。",
        maxLevel: 2,
        unlockCost: 204,
      },
    ],
  },
  {
    id: "tulipThunder",
    name: "郁金雷击",
    description: "召唤郁金花雷跳跃传导至附近敌人。",
    color: "#ffab86",
    advancedBehavior: "strike",
    unlockCost: 868,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.0, damage: 62, count: 1, radius: 50, delay: 0.44 },
      { cooldown: 3.6, damage: 80, count: 1, radius: 56, delay: 0.38 },
      { cooldown: 3.2, damage: 102, count: 2, radius: 62, delay: 0.32 },
      { cooldown: 2.85, damage: 126, count: 2, radius: 68, delay: 0.26 },
      { cooldown: 2.5, damage: 156, count: 2, radius: 76, delay: 0.2 },
    ],
    exclusiveUpgrades: [
      {
        id: "tulipThunderFocus",
        name: "郁金蓄雷",
        description: "提高雷击伤害与传导次数。",
        maxLevel: 2,
        unlockCost: 188,
      },
      {
        id: "tulipThunderTempo",
        name: "雷花速绽",
        description: "缩短郁金雷击的冷却时间。",
        maxLevel: 2,
        unlockCost: 208,
      },
    ],
  },
  {
    id: "eclipsePetalRain",
    name: "蚀瓣花雨",
    description: "降下蚀光花瓣叠加易伤标记。",
    color: "#f073a4",
    advancedBehavior: "meteor",
    unlockCost: 896,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 5.2, damage: 76, radius: 48, count: 1, fallTime: 0.74 },
      { cooldown: 4.7, damage: 96, radius: 54, count: 1, fallTime: 0.66 },
      { cooldown: 4.2, damage: 120, radius: 60, count: 2, fallTime: 0.58 },
      { cooldown: 3.8, damage: 148, radius: 66, count: 2, fallTime: 0.5 },
      { cooldown: 3.4, damage: 182, radius: 74, count: 2, fallTime: 0.42 },
    ],
    exclusiveUpgrades: [
      {
        id: "eclipsePetalRainFocus",
        name: "蚀力加深",
        description: "提高花瓣伤害与易伤叠加效果。",
        maxLevel: 2,
        unlockCost: 192,
      },
      {
        id: "eclipsePetalRainTempo",
        name: "花雨密集",
        description: "缩短蚀瓣花雨的冷却时间。",
        maxLevel: 2,
        unlockCost: 212,
      },
    ],
  },
  {
    id: "blueflameGarden",
    name: "蓝焰花园",
    description: "铺开蓝焰花田随时间扩大范围递增伤害。",
    color: "#92a7ff",
    advancedBehavior: "field",
    unlockCost: 924,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 4.4, damage: 16, count: 1, radius: 66, duration: 4.0, tickInterval: 0.42 },
      { cooldown: 4.0, damage: 24, count: 1, radius: 74, duration: 4.6, tickInterval: 0.4 },
      { cooldown: 3.6, damage: 34, count: 2, radius: 82, duration: 5.2, tickInterval: 0.38 },
      { cooldown: 3.2, damage: 46, count: 2, radius: 90, duration: 5.8, tickInterval: 0.36 },
      { cooldown: 2.85, damage: 60, count: 2, radius: 100, duration: 6.4, tickInterval: 0.34 },
    ],
    exclusiveUpgrades: [
      {
        id: "blueflameGardenFocus",
        name: "蓝焰浓缩",
        description: "提高花田伤害与最大范围。",
        maxLevel: 2,
        unlockCost: 196,
      },
      {
        id: "blueflameGardenTempo",
        name: "焰速蔓延",
        description: "缩短蓝焰花园的冷却时间。",
        maxLevel: 2,
        unlockCost: 216,
      },
    ],
  },
  {
    id: "scissorVine",
    name: "剪刃藤蔓",
    description: "交叉长出刃状藤蔓剪切范围内的敌人。",
    color: "#ef6872",
    advancedBehavior: "snare",
    unlockCost: 952,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.4, damage: 60, count: 2, range: 250, root: 0.64, bloomRadius: 54 },
      { cooldown: 3.05, damage: 78, count: 2, range: 280, root: 0.76, bloomRadius: 58 },
      { cooldown: 2.7, damage: 100, count: 3, range: 310, root: 0.88, bloomRadius: 62 },
      { cooldown: 2.4, damage: 124, count: 3, range: 340, root: 1.0, bloomRadius: 66 },
      { cooldown: 2.1, damage: 152, count: 3, range: 370, root: 1.14, bloomRadius: 72 },
    ],
    exclusiveUpgrades: [
      {
        id: "scissorVineFocus",
        name: "剪刃淬炼",
        description: "提高藤蔓伤害与剪切范围。",
        maxLevel: 2,
        unlockCost: 200,
      },
      {
        id: "scissorVineTempo",
        name: "蔓剪速切",
        description: "缩短剪刃藤蔓的冷却时间。",
        maxLevel: 2,
        unlockCost: 220,
      },
    ],
  },
  {
    id: "royalBudPulse",
    name: "皇室芽脉冲",
    description: "释放皇室脉冲，覆盖范围内的技能获得伤害加成。",
    color: "#a8d46b",
    advancedBehavior: "pulse",
    unlockCost: 980,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 5.0, damage: 44, radius: 110, waves: 1, growth: 290 },
      { cooldown: 4.5, damage: 60, radius: 130, waves: 1, growth: 310 },
      { cooldown: 4.0, damage: 80, radius: 150, waves: 2, growth: 330 },
      { cooldown: 3.6, damage: 102, radius: 170, waves: 2, growth: 350 },
      { cooldown: 3.2, damage: 128, radius: 190, waves: 2, growth: 370 },
    ],
    exclusiveUpgrades: [
      {
        id: "royalBudPulseFocus",
        name: "皇室恩泽",
        description: "提高脉冲伤害与增伤效果。",
        maxLevel: 2,
        unlockCost: 204,
      },
      {
        id: "royalBudPulseTempo",
        name: "芽脉冲频",
        description: "缩短皇室芽脉冲的冷却时间。",
        maxLevel: 2,
        unlockCost: 224,
      },
    ],
  },
  {
    id: "amberGearBurst",
    name: "琥珀齿轮",
    description: "发射旋转齿轮，嵌入原地持续切割触碰的敌人。",
    color: "#f1b86b",
    advancedBehavior: "lobbedBomb",
    unlockCost: 1008,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 3.6, damage: 58, count: 1, speed: 220, size: 14, splash: 52, range: 260 },
      { cooldown: 3.25, damage: 74, count: 1, speed: 240, size: 15, splash: 58, range: 280 },
      { cooldown: 2.9, damage: 94, count: 2, speed: 260, size: 16, splash: 64, range: 300 },
      { cooldown: 2.6, damage: 116, count: 2, speed: 280, size: 17, splash: 70, range: 320 },
      { cooldown: 2.3, damage: 142, count: 2, speed: 300, size: 18, splash: 78, range: 340 },
    ],
    exclusiveUpgrades: [
      {
        id: "amberGearBurstFocus",
        name: "齿轮锋锐",
        description: "提高齿轮伤害与旋转切割时间。",
        maxLevel: 2,
        unlockCost: 208,
      },
      {
        id: "amberGearBurstTempo",
        name: "急速齿转",
        description: "缩短琥珀齿轮的冷却时间。",
        maxLevel: 2,
        unlockCost: 228,
      },
    ],
  },
  {
    id: "auroraNeedle",
    name: "极光针雨",
    description: "凝聚极光之针以扇形洒落密集针雨。",
    color: "#c9a9ff",
    advancedBehavior: "beam",
    unlockCost: 1036,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 2.2, damage: 34, count: 3, speed: 480, pierce: 0, size: 6, range: 360 },
      { cooldown: 2.0, damage: 44, count: 3, speed: 510, pierce: 0, size: 7, range: 390 },
      { cooldown: 1.8, damage: 56, count: 4, speed: 540, pierce: 1, size: 8, range: 420 },
      { cooldown: 1.6, damage: 70, count: 4, speed: 570, pierce: 1, size: 9, range: 450 },
      { cooldown: 1.45, damage: 86, count: 5, speed: 600, pierce: 1, size: 10, range: 480 },
    ],
    exclusiveUpgrades: [
      {
        id: "auroraNeedleFocus",
        name: "极光淬针",
        description: "提高针雨伤害与覆盖角度。",
        maxLevel: 2,
        unlockCost: 212,
      },
      {
        id: "auroraNeedleTempo",
        name: "针雨密集",
        description: "缩短极光针雨的冷却时间。",
        maxLevel: 2,
        unlockCost: 232,
      },
    ],
  },
  {
    id: "grandPrismMeteor",
    name: "大棱镜彗星",
    description: "召来巨型棱镜彗星碎裂追踪敌人。",
    color: "#72cbff",
    advancedBehavior: "meteor",
    unlockCost: 1064,
    maxLevel: 5,
    statsByLevel: [
      { cooldown: 6.0, damage: 96, radius: 56, count: 1, fallTime: 0.7 },
      { cooldown: 5.4, damage: 122, radius: 62, count: 1, fallTime: 0.62 },
      { cooldown: 4.8, damage: 152, radius: 68, count: 2, fallTime: 0.54 },
      { cooldown: 4.3, damage: 186, radius: 74, count: 2, fallTime: 0.46 },
      { cooldown: 3.8, damage: 226, radius: 82, count: 2, fallTime: 0.38 },
    ],
    exclusiveUpgrades: [
      {
        id: "grandPrismMeteorFocus",
        name: "棱星碎裂",
        description: "提高彗星与小棱星伤害。",
        maxLevel: 2,
        unlockCost: 216,
      },
      {
        id: "grandPrismMeteorTempo",
        name: "彗星速召",
        description: "缩短大棱镜彗星的冷却时间。",
        maxLevel: 2,
        unlockCost: 236,
      },
    ],
  },
];
